-- MySQL Script generated by MySQL Workbench
-- 09/19/18 14:16:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema carRental
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema carRental
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `carRental` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `carRental` ;

-- -----------------------------------------------------
-- Table `carRental`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carRental`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cnh` CHAR(11) NULL,
  `cpf` CHAR(11) NULL,
  `cnpj` CHAR(14) NULL,
  `data_cadastro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `tipo_cliente` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC),
  UNIQUE INDEX `cnh_UNIQUE` (`cnh` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carRental`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carRental`.`marca` (
  `id_marca` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NULL,
  PRIMARY KEY (`id_marca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carRental`.`modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carRental`.`modelo` (
  `id_modelo` INT NOT NULL AUTO_INCREMENT,
  `preco` FLOAT NOT NULL,
  `id_marca` INT NOT NULL,
  `modelo` VARCHAR(45) NULL,
  `ano` INT NOT NULL,
  `combustivel` VARCHAR(45) NOT NULL,
  `transmissao` VARCHAR(45) NOT NULL,
  `num_portas` INT NOT NULL,
  `tanque` INT NOT NULL,
  PRIMARY KEY (`id_modelo`),
  INDEX `fk_modelo_marca1_idx` (`id_marca` ASC),
  CONSTRAINT `fk_modelo_marca1`
    FOREIGN KEY (`id_marca`)
    REFERENCES `carRental`.`marca` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carRental`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carRental`.`veiculo` (
  `renavam` CHAR(11) NOT NULL,
  `id_modelo` INT NOT NULL,
  `cor` VARCHAR(45) NOT NULL,
  `placa` CHAR(7) NULL,
  `lugares` INT NULL,
  `chassi` CHAR(17) NULL,
  `imagem` VARCHAR(45) NULL,
  `disponivel` TINYINT(1) NULL,
  PRIMARY KEY (`renavam`),
  INDEX `fk_veiculo_modelo1_idx` (`id_modelo` ASC),
  CONSTRAINT `fk_veiculo_modelo1`
    FOREIGN KEY (`id_modelo`)
    REFERENCES `carRental`.`modelo` (`id_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carRental`.`tipo_pag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carRental`.`tipo_pag` (
  `id_tipo_pag` INT NOT NULL AUTO_INCREMENT,
  `tipo_pag` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo_pag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carRental`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carRental`.`pagamento` (
  `nota_fiscal` INT NOT NULL AUTO_INCREMENT,
  `data_pag` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `valor` FLOAT NULL,
  `id_tipo_pag` INT NOT NULL,
  PRIMARY KEY (`nota_fiscal`),
  INDEX `fk_pagamento_tipo_pag1_idx` (`id_tipo_pag` ASC),
  CONSTRAINT `fk_pagamento_tipo_pag1`
    FOREIGN KEY (`id_tipo_pag`)
    REFERENCES `carRental`.`tipo_pag` (`id_tipo_pag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carRental`.`aluguel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carRental`.`aluguel` (
  `id_cliente` INT NOT NULL,
  `renavam` CHAR(11) NOT NULL,
  `check_in` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `check_out` DATETIME NULL,
  `nota_fiscal` INT NOT NULL,
  PRIMARY KEY (`id_cliente`, `renavam`),
  INDEX `fk_veiculo_has_cliente_cliente1_idx` (`id_cliente` ASC),
  INDEX `fk_veiculo_cliente_veiculo1_idx` (`renavam` ASC),
  INDEX `fk_aluguel_pagamento1_idx` (`nota_fiscal` ASC),
  CONSTRAINT `fk_veiculo_has_cliente_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `carRental`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_veiculo_cliente_veiculo1`
    FOREIGN KEY (`renavam`)
    REFERENCES `carRental`.`veiculo` (`renavam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluguel_pagamento1`
    FOREIGN KEY (`nota_fiscal`)
    REFERENCES `carRental`.`pagamento` (`nota_fiscal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carRental`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carRental`.`telefone` (
  `telefone` VARCHAR(11) NOT NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`telefone`, `id_cliente`),
  INDEX `fk_telefone_cliente1_idx` (`id_cliente` ASC),
  CONSTRAINT `fk_telefone_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `carRental`.`cliente` (`id_cliente`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carRental`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carRental`.`email` (
  `email` VARCHAR(60) NOT NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`email`, `id_cliente`),
  INDEX `fk_table2_cliente1_idx` (`id_cliente` ASC),
  CONSTRAINT `fk_table2_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `carRental`.`cliente` (`id_cliente`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
